config/routes.rb
Store::Application.routes.draw do
  root 'products#index'

  controller :cart do
    get "/checkout",  to: "cart#show"
    post "/checkout", to: "cart#charge"
  end

  resources :invoices, only: [:show]

  resources :products, only: [:index, :show] do
    get '/c/:category_id', on: :collection, action: :index, as: :category
    post   'cart', on: :member, action: :add_to_cart, as: :add_to_cart
    delete 'cart', on: :member, action: :delete_from_cart, as: :delete_from_cart
  end

  namespace :admin do
    get '/', to: redirect('/admin/categories')

    resources :products
    resources :categories do
      resources :products, only: [:index]
    end

    resources :discounts, only: [:destroy]
    resources :product_pricings, only: [:destroy]
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, length: { minimum: 4 }
  validate :parent_in_available_parents

  has_many :products

  belongs_to :parent, class_name: "Category"
  has_many :children, class_name: "Category", foreign_key: "parent_id"

  scope :first_level, -> { where(parent_id: nil) }
  scope :third_level_categories, -> { joins(parent: :parent) }

  ##
  # Finds valid parent categories for a single category instance
  #
  # Excludes self and third level categories
  def available_parents
    s = self.class.all
    if self.persisted?
      s = s.where(["id != ?", self.id])
    end

    if self.class.third_level_categories.present?
      s = s.where(["id not in (?)", self.class.third_level_categories.collect(&:id)])
    end
    s
  end

  private

  def parent_in_available_parents
    if parent.present? && !available_parents.include?(parent)
      errors.add(:parent_id, "is not allowed")
    end
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  before_filter :get_category, only: [:edit, :show, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path, notice: "category #{@category.name} created"
    else
      render action: "new"
    end
  end

  def update
    if @category.update_attributes(category_params)
      redirect_to admin_categories_path, notice: "category #{@category.name} updated"
    else
      render action: "edit"
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :parent_id)
  end

  def get_category
    @category = Category.find(params[:id])
    redirect_to admin_categories_path unless @category
  end
end

app/views/admin/categories/_form.html.haml
= simple_form_for([:admin, @category], html: {class: 'form-horizontal' }) do |f|
  = f.error_notification

  = f.input :name
  = f.input :parent_id, collection: @category.available_parents

  = f.button :submit, "Save", class: "btn-primary"

app/views/admin/categories/edit.html.haml
%h1
  Edit category
  %strong= @category.name

= render "form"

app/views/admin/categories/index.html.haml
%h1
  Categories

- @categories.each_slice(4) do |categories|
  .row
    - categories.each do |category|
      .col-md-3.text-center
        = link_to [:edit, :admin, category] do
          %img.img-thumbnail{src: "http://placehold.it/160x160"}
        %p
          = link_to category.name, [:edit, :admin, category]
          = link_to "(#{category.products.size})", [:admin, category, :products]

%hr
%p
  = link_to "Add", new_admin_category_path, class: "btn btn-primary"

app/views/admin/categories/new.html.haml
%h1
  Add a category

= render "form"