config/routes.rb
Store::Application.routes.draw do
  root 'products#index'

  controller :cart do
    get "/checkout",  to: "cart#show"
    post "/checkout", to: "cart#charge"
  end

  resources :invoices, only: [:show]

  resources :products, only: [:index, :show] do
    get '/c/:category_id', on: :collection, action: :index, as: :category
    post   'cart', on: :member, action: :add_to_cart, as: :add_to_cart
    delete 'cart', on: :member, action: :delete_from_cart, as: :delete_from_cart
  end

  namespace :admin do
    get '/', to: redirect('/admin/categories')

    resources :products
    resources :categories do
      resources :products, only: [:index]
    end

    resources :discounts, only: [:destroy]
    resources :product_pricings, only: [:destroy]
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category, counter_cache: true
  has_many :product_pricings, dependent: :destroy
  has_many :discounts, dependent: :destroy

  accepts_nested_attributes_for :product_pricings, reject_if: lambda {|attributes|
    attributes['price'].blank?
  }

  accepts_nested_attributes_for :discounts, reject_if: lambda {|attributes|
    attributes['amount'].blank?
  }

  validates :name, length: { minimum: 4, maximum: 200 }
  validates :in_stock, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :category, presence: true

  def human_price_with_discount(d, p)
    "#{price_with_discount(d, p)}€"
  end

  ##
  # Calculate the price given the discount and pricing
  #
  # Ensures no spillover to different pricing period
  def price_with_discount(d, p)
    price_at([d.takes_effect_on, p.takes_effect_on].max)
  end

  ##
  # Calculate the price at any given time, accounting for discount
  def price_at(time)
    p = pricing_at(time).price
    if discount_at(time)
      p - discount_at(time).calculate_discount(p)
    else
      p
    end
  end

  def price
    price_at Time.now
  end

  def human_price
    "#{price}€"
  end

  def out_of_stock?
    in_stock <= 0
  end

  def discounted?
    discount_at(Time.now).present?
  end

  def current_pricing
    pricing_at(Time.now)
  end

  def active_discounts_for(pricing)
    discounts.where([
      "takes_effect_on between :start and :end or
      ends_on between :start and :end or
      takes_effect_on < :start and ends_on > :end",
      start: pricing.takes_effect_on,
      end: next_pricing(pricing).takes_effect_on
    ])
  end

  def next_pricing(pricing)
    product_pricings.where(["takes_effect_on > ?", pricing.takes_effect_on]).order("takes_effect_on asc").first || NullPricing.new
  end

  private

  def discount_at(time)
    discounts.where(["? between takes_effect_on and ends_on", time]).first
  end

  def pricing_at(time)
    product_pricings.order("takes_effect_on desc").where(["takes_effect_on <= ?", time]).first
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  before_filter :get_product, only: [:edit, :show, :update, :destroy]
  before_filter :get_category, only: [:index]

  def index
    @products = Product.all
    if @category
      @products = @products.where(category: @category)
    end
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    @product.product_pricings.first_or_initialize.takes_effect_on = Time.now
    if @product.save
      redirect_to admin_products_path, notice: "Product #{@product.name} created"
    else
      render action: "new"
    end
  end

  def update
    if @product.update_attributes(product_params)
      redirect_to product_redirection_path, notice: "Product #{@product.name} updated"
    else
      render action: "edit"
    end
  end

  private

  def product_redirection_path
    if @product.category
      [:admin, @product.category, :products]
    else
      admin_products_path
    end
  end

  def product_params
    params.require(:product).permit(:name, :description, :in_stock, :category_id,
      product_pricings_attributes: [:price, :takes_effect_on],
      discounts_attributes: [:takes_effect_on, :ends_on, :amount, :percentage_based]
    )
  end

  def get_product
    @product = Product.find(params[:id], include: [:discounts, :product_pricings])
    redirect_to admin_products_path unless @product
  end

  def get_category
    if params[:category_id]
      @category = Category.find(params[:category_id])
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :get_category
  before_filter :get_product, except: [:index]

  def index
    @products = if @category
      @category.products
    else
      Product.all
    end
  end

  def show
  end

  def add_to_cart
    unless cart.add_item @product
      flash[:notice] = "#{product.name} is out of stock, you cannot add any more!"
    end
    redirect_to @product
  end

  def delete_from_cart
    cart.delete_item @product
    redirect_to :back
  end

  private

  def get_category
    if params[:category_id]
      @category = Category.find params[:category_id]
    end
  end

  def get_product
    @product = Product.find(params[:id])
  end
end

app/views/admin/products/_form.html.haml
= simple_form_for([:admin, @product], html: { class: 'form-horizontal col-md-8 col-md-pull-4 product-form' }) do |f|
  = f.error_notification

  = f.input :name
  = f.input :description, input_html: { rows: 8 }
  = f.input :in_stock, input_html: { min: 0 }
  = f.input :category do
    = f.input_field :category_id, collection: Category.all, required: true

  - if @product.persisted?
    %h3
      Set new price

  = render "new_pricing", f: f

  - if @product.persisted?
    %h3
      Add a discount

    = render "new_discount", f: f

  = f.button :submit, "Save", class: "btn-primary"

app/views/admin/products/_new_discount.html.haml
= f.simple_fields_for :discounts, @product.discounts.build do |pf|
  = pf.input :takes_effect_on, :wrapper => :addon do
    = pf.input_field :takes_effect_on, as: :string
    %span.input-group-addon>
      %i.glyphicon.glyphicon-calendar

  - if f.error(:"discounts.takes_effect_on")
    .row
      .col-md-push-2.col-md-5= f.error(:"discounts.takes_effect_on")
      %br
      %br

  = pf.input :ends_on, :wrapper => :addon do
    = pf.input_field :ends_on, as: :string
    %span.input-group-addon>
      %i.glyphicon.glyphicon-calendar

  = pf.input :percentage_based, as: :stacked_radio_buttons
  = pf.input :amount do
    = pf.input_field :amount
    - if f.error(:"discounts.amount")
      = f.error(:"discounts.amount")
  = pf.hint "Flat amount when not percentage based, % of regular price otherwise"

app/views/admin/products/_new_pricing.html.haml
= f.simple_fields_for :product_pricings, @product.product_pricings.build do |pf|
  = pf.input :price do
    = pf.input_field :price
    - if f.error(:"product_pricings.price")
      = f.error(:"product_pricings.price")

  - if @product.persisted?
    = pf.input :takes_effect_on, :wrapper => :addon do
      = pf.input_field :takes_effect_on, as: :string
      %span.input-group-addon>
        %i.glyphicon.glyphicon-calendar

    - if f.error(:"product_pricings.takes_effect_on")
      .row
        .col-md-push-2.col-md-5= f.error(:"product_pricings.takes_effect_on")

app/views/admin/products/edit.html.haml
%h1
  Edit product
  %strong{title: @product.name}= truncate @product.name

  - if @product.category
    .pull-right
      %small
        = link_to [:admin, @product.category, :products], class: "text-muted" do
          ←
          = @product.category.name

.row
  .col-md-4.col-md-push-8
    %h3
      Pricing history

    = render @product.product_pricings.order("takes_effect_on asc")
  = render "form"

app/views/admin/products/index.html.haml
%h1
  Products
  - if @category
    %small
      within
      = @category.name

- @products.each_slice(4) do |products|
  .row
    - products.each do |product|
      .col-md-3.text-center
        = link_to [:edit, :admin, product] do
          %img.img-thumbnail{src: "http://placehold.it/160x160"}
          %p{title: product.name}= truncate product.name
        - if product.out_of_stock?
          %span.text-warning
            %strong= product.name
            is out of stock!
        - else
          Stock:
          = product.in_stock

%hr
%p
  - if Category.count > 0
    = link_to "Add", new_admin_product_path, class: "btn btn-primary"
  - else
    Add a category before adding a product!

app/views/admin/products/new.html.haml
%h1
  Add a product

.row
  .col-md-4.col-md-push-8
  = render "form"