config/routes.rb
Store::Application.routes.draw do
  root 'products#index'

  controller :cart do
    get "/checkout",  to: "cart#show"
    post "/checkout", to: "cart#charge"
  end

  resources :invoices, only: [:show]

  resources :products, only: [:index, :show] do
    get '/c/:category_id', on: :collection, action: :index, as: :category
    post   'cart', on: :member, action: :add_to_cart, as: :add_to_cart
    delete 'cart', on: :member, action: :delete_from_cart, as: :delete_from_cart
  end

  namespace :admin do
    get '/', to: redirect('/admin/categories')

    resources :products
    resources :categories do
      resources :products, only: [:index]
    end

    resources :discounts, only: [:destroy]
    resources :product_pricings, only: [:destroy]
  end
end

app/views/layouts/_cart.html.haml
- if cart.has_products?
  .alert.alert-info
    You have
    = pluralize cart.cart_lines.size, "product"
    in your cart.

    %strong= link_to "Check out", checkout_path

app/views/layouts/_category_list.html.haml
%h4
  Many types of products

%ul#category-list
  = render Category.first_level

app/views/layouts/_header.html.haml
%nav.navbar.navbar-fixed-top.navbar-inverse
  .container
    %ul.nav.navbar-nav
      %li= link_to "Categories", admin_categories_path
      %li= link_to "All products", admin_products_path

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    .alert{class: "alert-#{name == :notice ? "success" : "danger"}"}
      %a.close{data: {dismiss: "alert"}}
        &#215;
      %div{id: "flash_#{name}"}=msg

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title= content_for?(:title) ? yield(:title) : "Store admin"
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body.admin
    = render "layouts/header"

    %main{role: "main"}
      .container
        = render "layouts/messages"
        = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= content_for?(:title) ? yield(:title) : "SuperStore"
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    %main{role: "main"}
      .container
        %h1
          Welcome to
          = link_to "SuperStore", root_path
          \- We sell products.
        = render "layouts/messages"
        = render "layouts/cart" unless controller_name == "cart"

        = yield

app/views/layouts/blank.html.haml
!!!
%html
  %head
    = stylesheet_link_tag "application", :media => "all"

  %body
    %main{role: "main"}
      .container
        = yield

app/views/layouts/email.html.haml
!!!
%html
  %head
    :css
      body {font-family:sans-serif}

  %body
    = yield